name: Detect-action
 
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
 
jobs:
  build:
    runs-on: [ ubuntu-latest ]
 
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Run Synopsys Detect
      uses: synopsys-sig/detect-action@SIGINT-119
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        detect-version: 9.3.0
        blackduck-url: ${{ secrets.BLACKDUCK_URL }}
        blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
        # scan-mode: RAPID
        fail-on-all-policy-severities: false
        detect-trust-cert: true
