name: Detect-action
 
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
 
jobs:
  build:
    runs-on: [ ubuntu-latest ]
 
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Run Synopsys Detect
      uses: synopsys-sig/detect-action@main
      env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_VERSION: 8.2.0
          DETECT_PROJECT_CODELOCATION_UNMAP: true
          DETECT_TOOLS_EXCLUDED: SIGNATURE_SCAN
          DETECT_WAIT_FOR_RESULTS: true
          DETECT_TIMEOUT: 3600  
          DETECT_CLEANUP: false
          DETECT_POLICY_CHECK_FAIL_ON_SEVERITIES: BLOCKER,CRITICAL,MAJOR
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        detect-version: 9.3.0
        blackduck-url: ${{ secrets.BLACKDUCK_URL }}
        blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
        # scan-mode: RAPID
        fail-on-all-policy-severities: false
        detect-trust-cert: TRUE